In [23]:
import numpy as np
import pandas as pd

In [19]:
data = {
    'Name':['Naran','Ram','Peter','Linda'],
    'Age' : [21,30,35,43],
    'City': ['Kathmandu','Bhaktapur','Berlin','London'],
    'Salary' : [100000,40000,42000,80000]
}
df =pd.DataFrame(data)

In [18]:
df

    Name  Age       City  Salary
0  Naran   21  Kathmandu  100000
1    Ram   30  Bhaktapur   40000
2  Peter   35     Berlin   42000
3  Linda   43     London   80000

In [28]:
data_list = [
    ['john',28,'New York',65000],
    ['Anna',34,'Paris',70000],
    ['Peter',29,'Berlin',62000],
    ['linda',42,'London',85000]    
]

df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary" ]
df2=pd.DataFrame(data_list,columns=columns)
print(df2)

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  linda   42    London   85000

## Selecting and Indexing of Columns

In [34]:
df2[['Name','City']]

    Name      City
0   john  New York
1   Anna     Paris
2  Peter    Berlin
3  linda    London

## Adding a new column

In [37]:
df2['Designation'] = ['Manager','Coder','Doctor','Developer']
df2

    Name  Age      City  Salary Designation
0   john   28  New York   65000     Manager
1   Anna   34     Paris   70000       Coder
2  Peter   29    Berlin   62000      Doctor
3  linda   42    London   85000   Developer

## Removing columns

In [45]:
df2.drop(['City','Salary'],axis = 1 )

    Name  Age
0   john   28
1   Anna   34
2  Peter   29
3  linda   42

In [47]:
df2.drop(0,axis = 0 )

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  linda   42  London   85000

In [48]:
df2

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  linda   42    London   85000

## Selecting Rows

In [54]:
df2.loc[[0,1]] # loc = location it is keyword

   Name  Age      City  Salary
0  john   28  New York   65000
1  Anna   34     Paris   70000

In [56]:
df2.iloc[3]

Name       linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [60]:
df2

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  linda   42    London   85000

In [59]:
#Selecting subsets of rows and columns 

df2.loc[[0 , 1]] [["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [61]:
df2.loc[[2,3]] [["Name","Age"]]

    Name  Age
2  Peter   29
3  linda   42

### Conditional Selection

In [62]:
df2

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  linda   42    London   85000

### I only want to see those people whose age is above 30

In [64]:
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  linda   42  London   85000

### I only want people whose age is above 30 and their city must be paris

In [66]:
df2[(df2["Age"]> 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000