In [1]:
import numpy as np 
import pandas as pd

## GroupBy

In [2]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

### Group by Cagegory and calculate the sum of Sales

In [8]:
cat =df.groupby('Category') [ 'Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

### Group by Store and calculate the sum of Sales

In [10]:
st= df.groupby('Store') ['Sales'].sum()
st

Store
S1    720
S2    780
Name: Sales, dtype: int64

### Group by multiple columns
### Group by Category and store

In [13]:
cat =  df.groupby(['Category','Store']) ['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

## Aggregation 
#### It means combining multiple values into a single summary result. It’s commonly used when you want statistics like sum, mean, count, min, max, etc., from your dataset.

## Basic Aggregation Methods

```python
# -------------------------------
# Basic Aggregation Methods
# -------------------------------

df['Marks'].sum()      # Returns total of Marks
df['Marks'].mean()     # Returns average Marks
df['Marks'].count()    # Counts non-null values
df['Marks'].min()      # Returns minimum value
df['Marks'].max()      # Returns maximum value
df['Marks'].median()   # Returns median value
df['Marks'].std()      # Returns standard deviation

In [16]:
mean =df['Sales'].mean()
print(mean)

187.5

In [17]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [23]:
# 'mode' does not work directly inside .agg() because it can return multiple values
result = df['Sales'].agg(['mean', 'min', 'max'])
result['mode'] = df['Sales'].mode().iloc[0]  # first mode
print(result)

mean    187.5
min     100.0
max     300.0
mode    200.0
Name: Sales, dtype: float64